version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/stac_fastapi"
    schedule:
      interval: weekly
