services:
  app:
    image: stac-utils/stac-fastapi-pgstac
    build: .
    environment:
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
      - PGHOST=database
      - PGPORT=5432
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - USE_API_HYDRATE=${USE_API_HYDRATE:-false}
      - ENABLE_TRANSACTIONS_EXTENSIONS=${ENABLE_TRANSACTIONS_EXTENSIONS:-false}
      - ENABLE_CATALOGS_EXTENSION=${ENABLE_CATALOGS_EXTENSION:-false}
      - STAC_FASTAPI_TITLE=${STAC_FASTAPI_TITLE:-STAC FastAPI PgSTAC}
      - STAC_FASTAPI_DESCRIPTION=${STAC_FASTAPI_DESCRIPTION:-STAC FastAPI with PGStac Backend}
      - STAC_FASTAPI_VERSION=${STAC_FASTAPI_VERSION:-6.x}
      - STAC_FASTAPI_LANDING_ID=${STAC_FASTAPI_LANDING_ID:-stac-fastapi-pgstac-landing}
    ports:
      - "8082:8082"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
    depends_on:
      database:
        condition: service_healthy
    command: ["uvicorn", "stac_fastapi.pgstac.app:create_app", "--factory", "--host", "0.0.0.0", "--port", "8082", "--reload"]
    develop:
      watch:
        - action: rebuild
          path: ./stac_fastapi/pgstac

  database:
    image: ghcr.io/stac-utils/pgstac:v0.9.11
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgis"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

networks:
  default:
    name: stac-fastapi-network
