services:
  tests:
    image: stac-utils/stac-fastapi-pgstac-test
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      - ENVIRONMENT=local
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - USE_API_HYDRATE=${USE_API_HYDRATE:-false}
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./tests:/app/tests
    depends_on:
      - database
    command: bash -c "python -m pytest -s -vv"
