services:
  app-nginx:
    ports:
      - "8083:8083"
    extends:
      file: compose.yml
      service: app
    command: ["uvicorn", "stac_fastapi.pgstac.app:create_app", "--factory", "--host", "0.0.0.0", "--port", "8083", "--proxy-headers", "--forwarded-allow-ips", "*", "--root-path", "/api/v1/pgstac"]

  nginx:
    image: nginx
    ports:
      - ${STAC_FASTAPI_NGINX_PORT:-8080}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-nginx
    command: [ "nginx-debug", "-g", "daemon off;" ]
