version: '3'
services:
  nginx:
    image: nginx
    ports:
      - ${STAC_FASTAPI_NGINX_PORT:-80}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    command: [ "nginx-debug", "-g", "daemon off;" ]
  app:
    environment:
      - UVICORN_ROOT_PATH=/api/v1/pgstac
