site_name: stac-fastapi
site_description: STAC FastAPI.

# Repository
repo_name: 'stac-utils/stac-fastapi'
repo_url: 'https://github.com/stac-utils/stac-fastapi'
edit_uri: 'blob/master/docs/src/'


# Social links
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/stac-utils'

# Layout
nav:
  - Home: 'index.md'
  - API:
    - stac_fastapi.api: api/stac_fastapi/api/index.md
    - stac_fastapi.extensions: api/stac_fastapi/extensions/index.md
    - stac_fastapi.types: api/stac_fastapi/types/index.md
    - stac_fastapi.pgstac: api/stac_fastapi/pgstac/index.md
  - Development - Contributing: 'contributing.md'
  - Release Notes: 'release-notes.md'

plugins:
  - search

# Theme
theme:
  icon:
    logo: 'material/home'
    repo: 'fontawesome/brands/github'
  name: 'material'
  language: 'en'
  font:
    text: 'Nunito Sans'
    code: 'Fira Code'

extra_css:
  - stylesheets/extra.css

# These extensions are chosen to be a superset of Pandoc's Markdown.
# This way, I can write in Pandoc's Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
markdown_extensions:
    - admonition
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem
    - pymdownx.caret:
        insert: false
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.escapeall:
        hardbreak: true
        nbsp: true
    - pymdownx.magiclink:
        hide_protocol: true
        repo_url_shortener: true
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true
